### ISSUE TITLE
Add_host record issue

### ISSUE THREAD

**Issue by asainsbury** [xoanmi/ansible-infoblox#39]
Hi there,

After the update to 2.5, the example you give in the README fails to create a host record, it now throws the following message:

>The full traceback is:
Traceback (most recent call last):
  File "/var/folders/_p/z3d2ljqx3xdfkjgr9q3z2pfw0000gn/T/ansible_nqxG4i/ansible_module_infoblox_2_5.py", line 2205, in <module>
    main()
  File "/var/folders/_p/z3d2ljqx3xdfkjgr9q3z2pfw0000gn/T/ansible_nqxG4i/ansible_module_infoblox_2_5.py", line 1915, in main
    host, address, network_ref, comment, ttl, extattrs)
  File "/var/folders/_p/z3d2ljqx3xdfkjgr9q3z2pfw0000gn/T/ansible_nqxG4i/ansible_module_infoblox_2_5.py", line 1067, in create_host_record
    return self.invoke("post", "record:host", ok_codes=(200, 201, 400), json=model)
  File "/var/folders/_p/z3d2ljqx3xdfkjgr9q3z2pfw0000gn/T/ansible_nqxG4i/ansible_module_infoblox_2_5.py", line 229, in invoke
    raise Exception(payload["text"])
Exception: IP address for the Host record is missing.

Works fine with 2.4.

I haven't checked all the other functions yet, but will start to write a set of test plays to try to catch this sort of thing.

Thanks,
/Andy

**Comment by asainsbury** [comment]
Duplicate issue, and I can make the changes and create a new PR.
